timezone: America/Los_Angeles
encoding: utf-8
markdown: kramdown
domain: www.edmatrix.org
layout: default
exclude:
  - README.md
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "stds"
    values:
      layout: "standard"
collections:
  stds:
    output: true
    permalink: /stds/:path.html
