timezone: America/Los_Angeles
encoding: utf-8
markdown: kramdown
title: EdMatrix
domain: www.edmatrix.org
layout: default
exclude:
  - README.md
  - _stds/Template.md
  - _orgs/Template.md
  - docker-compose.yml
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "stds"
    values:
      layout: "standard"
  -
    scope:
      path: ""
      type: "orgs"
    values:
      layout: "organization"
  -
    scope:
      path: ""
      type: "stds2"
    values:
      layout: "standard"
  -
    scope:
      path: ""
      type: "orgs2"
    values:
      layout: "organization"
collections:
  stds:
    output: true
    permalink: /stds/:path.html
  orgs:
    output: true
    permalink: /orgs/:path.html
  stds2:
    output: true
    permalink: /v2/stds/:path.html
  orgs2:
    output: true
    permalink: /v2/orgs/:path.html
  posts:
    output: true
    permalink: /news/:path.html
