# Builds and hosts a Jekyll site locally
# Launch: docker-compose up
# Then browse to http://localhost:4000
# Close: docker-compose down
# To keep this out of your website, add "docker-compose.yml" to the "exclude" list in your _config.yml
version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    environment:
      - "JEKYLL_GITHUB_TOKEN:"
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    tty: true